### PR TITLE
Push, pull and yank for single file

### PR DESCRIPTION
**Pull request by darkofabijan**

### CODE REVIEW

**Comment by shiroyasha** [comment]
The code looks good. 🏆 

I need automated runs of go-lint and tests on Semaphore to give final approval.

**Comment by darkofabijan** [comment]
@shiroyasha Thanks! 

@vendelin8 can you please set up that on your `vendelin8` oragnization and add two of us as organization members?

**Comment by vendelin8** [comment]
@shiroyasha Please check out the current state about goling and go vet. I added a corresponding part to README.md about initialization.

@darkofabijan What do you mean by this organization question? I found this:
https://help.github.com/en/articles/adding-organization-members-to-a-team
But there's no such part in my profile. I found a button on
https://github.com/settings/organizations
About turning my account into an organization. Is that something you'd like?

**Comment by darkofabijan** [comment]
@vendelin8 I meant Semaphore organization vendelin8.semaphoreci.com.

**Comment by vendelin8** [comment]
@darkofabijan Ok. I'm a little busy today, but I'll do it until tomorrow morning.

**Comment by vendelin8** [comment]
I added you @darkofabijan and @shiroyasha to my new organization `https://semaphore-artifact.semaphoreci.com` . I tried to create a new project from the artifact repo with the current version of `.semaphore/semaphore.yml` from the `dev` branch, but all I got was the endless spinner with the text `Commit & start the workflow`.

**Comment by vendelin8** [comment]
Done. Please check.

**Pull request merged**
